// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SwitchgearApi.Data;

#nullable disable

namespace SwitchgearApi.Migrations
{
    [DbContext(typeof(SwitchgearDbContext))]
    [Migration("20260626045044_AddProductName")]
    partial class AddProductName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SwitchgearApi.Models.CubicleDeviceExtraction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuxControlVoltage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CBRating")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CTRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CbBreakingCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CbMakingCapacity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CbMechanismType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CbNumberOfPoles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("CtAccuracyClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtBurden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtCoreType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviationReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentPackageId")
                        .HasColumnType("int");

                    b.Property<string>("DsCount")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DsOperatingMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EsPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractionPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlaggedForReview")
                        .HasColumnType("bit");

                    b.Property<string>("FunctionalPosition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PanelType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProtectionFunctions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelayAuxVoltage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelayCommunicationProtocol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RelayModel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SaPresent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceBoundingBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourcePage")
                        .HasColumnType("int");

                    b.Property<int?>("SwitchgearInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("VTRatio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtAccuracyClass")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtBurden")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VtInsulationLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentPackageId");

                    b.HasIndex("SwitchgearInstanceId");

                    b.ToTable("CubicleDeviceExtractions");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DeviationItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedField")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocumentPackageId")
                        .HasColumnType("int");

                    b.Property<string>("EngineersComment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Resolved")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.PrimitiveCollection<string>("SourcePageNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SuggestedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentPackageId");

                    b.HasIndex("Resolved");

                    b.HasIndex("Severity");

                    b.ToTable("DeviationItems");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DeviceSelection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbbArticleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<int>("CubicleId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CubicleId");

                    b.ToTable("DeviceSelections");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DocumentPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("OverallConfidence")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UploadedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("XmlOutput")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.HasIndex("UploadedAt");

                    b.ToTable("DocumentPackages");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DocumentPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Classification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ClassificationConfidence")
                        .HasColumnType("float");

                    b.Property<DateTime>("ClassifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentPackageId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PageNumber")
                        .HasColumnType("int");

                    b.Property<string>("RawContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentPackageId");

                    b.ToTable("DocumentPages");
                });

            modelBuilder.Entity("SwitchgearApi.Models.ExtractedParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<int>("DocumentPackageId")
                        .HasColumnType("int");

                    b.Property<string>("ExtractionPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExtractionReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FlaggedForReview")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsAbbDefault")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceBoundingBox")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SourcePageNumber")
                        .HasColumnType("int");

                    b.Property<string>("SourceText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SwitchgearInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("SwitchgearInstanceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConfidenceScore");

                    b.HasIndex("DocumentPackageId");

                    b.HasIndex("SwitchgearInstanceId");

                    b.ToTable("ExtractedParameters");
                });

            modelBuilder.Entity("SwitchgearApi.Models.SwitchgearCubicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AbbArticleNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AbbProductFamily")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("ConfidenceScore")
                        .HasColumnType("float");

                    b.Property<int>("DocumentPackageId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("SwitchgearInstanceId")
                        .HasColumnType("int");

                    b.Property<string>("TopologyWarning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentPackageId");

                    b.HasIndex("SwitchgearInstanceId");

                    b.ToTable("SwitchgearCubicles");
                });

            modelBuilder.Entity("SwitchgearApi.Models.SwitchgearInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DocumentPackageId")
                        .HasColumnType("int");

                    b.Property<int>("InstanceIndex")
                        .HasColumnType("int");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopologySummary")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DocumentPackageId");

                    b.ToTable("SwitchgearInstances");
                });

            modelBuilder.Entity("SwitchgearApi.Models.CubicleDeviceExtraction", b =>
                {
                    b.HasOne("SwitchgearApi.Models.DocumentPackage", "DocumentPackage")
                        .WithMany()
                        .HasForeignKey("DocumentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwitchgearApi.Models.SwitchgearInstance", "SwitchgearInstance")
                        .WithMany()
                        .HasForeignKey("SwitchgearInstanceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DocumentPackage");

                    b.Navigation("SwitchgearInstance");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DeviationItem", b =>
                {
                    b.HasOne("SwitchgearApi.Models.DocumentPackage", "DocumentPackage")
                        .WithMany("Deviations")
                        .HasForeignKey("DocumentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentPackage");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DeviceSelection", b =>
                {
                    b.HasOne("SwitchgearApi.Models.SwitchgearCubicle", "Cubicle")
                        .WithMany("Devices")
                        .HasForeignKey("CubicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cubicle");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DocumentPage", b =>
                {
                    b.HasOne("SwitchgearApi.Models.DocumentPackage", "DocumentPackage")
                        .WithMany("Pages")
                        .HasForeignKey("DocumentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentPackage");
                });

            modelBuilder.Entity("SwitchgearApi.Models.ExtractedParameter", b =>
                {
                    b.HasOne("SwitchgearApi.Models.DocumentPackage", "DocumentPackage")
                        .WithMany("Parameters")
                        .HasForeignKey("DocumentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwitchgearApi.Models.SwitchgearInstance", "SwitchgearInstance")
                        .WithMany("Parameters")
                        .HasForeignKey("SwitchgearInstanceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DocumentPackage");

                    b.Navigation("SwitchgearInstance");
                });

            modelBuilder.Entity("SwitchgearApi.Models.SwitchgearCubicle", b =>
                {
                    b.HasOne("SwitchgearApi.Models.DocumentPackage", "DocumentPackage")
                        .WithMany("Lineup")
                        .HasForeignKey("DocumentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SwitchgearApi.Models.SwitchgearInstance", "SwitchgearInstance")
                        .WithMany("Cubicles")
                        .HasForeignKey("SwitchgearInstanceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DocumentPackage");

                    b.Navigation("SwitchgearInstance");
                });

            modelBuilder.Entity("SwitchgearApi.Models.SwitchgearInstance", b =>
                {
                    b.HasOne("SwitchgearApi.Models.DocumentPackage", "DocumentPackage")
                        .WithMany("Instances")
                        .HasForeignKey("DocumentPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentPackage");
                });

            modelBuilder.Entity("SwitchgearApi.Models.DocumentPackage", b =>
                {
                    b.Navigation("Deviations");

                    b.Navigation("Instances");

                    b.Navigation("Lineup");

                    b.Navigation("Pages");

                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("SwitchgearApi.Models.SwitchgearCubicle", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("SwitchgearApi.Models.SwitchgearInstance", b =>
                {
                    b.Navigation("Cubicles");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
